from Transwriter import Transwriter

if __name__ == '__main__':
    t = Transwriter()
    t.save_path="test"
    t.new_page()
    t.draw_pic()
    t.title("The Byakuyakoku Collection")
    t.author("apin")
    ab = t.get_lines_from_file("txt/abstruction")
    t.abstract(ab[0])
    t.indexterms("Byakuyakoku Enkanomiya")
    t.first_heading("content")
    vol1 = t.get_lines_from_file("txt/vol1")
    t.content("vol i", vol1)
    # vol2 = t.get_lines_from_file("txt/vol2")
    # t.content("vol ii", vol2)
    # vol3 = t.get_lines_from_file("txt/vol3")
    # t.content("vol iii", vol3)
    # vol4 = t.get_lines_from_file("txt/vol4")
    # t.content("vol iv", vol4)
    # vol5 = t.get_lines_from_file("txt/vol5")
    # t.content("vol v", vol5)
    t.acknowledgments("")
    t.add_references("baiyeguowangshi", "abeiduo shatang xiangling", (1, 12, 23))
    t.add_references("baiyeguochenhunji", "xiangling zhongli alisi", (2, 2, 3))
    t.save_paper()
    print(t.get_txt_size("REFERENCES", 30))
